name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lua-version:
          - "5.1"
          - "5.2"
          - "5.3"
          - "5.4"
          - "luajit-2.0.5"
          - "luajit-openresty"
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    -
      name: Setup Lua ${{ matrix.lua-version }}
      uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: ${{ matrix.lua-version }}
    -
      name: Setup Luarocks
      uses: leafo/gh-actions-luarocks@v4
    -
      name: Install Tools
      run: |
        sudo apt install libmagic-dev lcov -y
        luarocks install assert
        luarocks install io-fileno
    -
      name: Install
      run: |
        luarocks make LIBMAGIC_COVERAGE=1
    -
      name: Run Test
      run: |
        lua ./test/libmagic_test.lua
    -
      name: Generate coverage reports
      run: |
        sh ./covgen.sh
    -
      name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage/lcov.info
        flags: unittests
